# Basic
title: Realank
subtitle: こんにちは.
welcome_message: 大家好我是Realank
description: 目前正在学习日语，欢迎交流
creator: <a href="https://github.com/Realank">@realank</a>

url: "http://realank.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 文章
    description: 访问文章

nav:
    - {title: 关于, description: 了解更多关于我, url: './about'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Social
social:
    github: realank
    mail: realank@126.com
